
package GUI;

import Classes.Configuracao;
import DAO.Util.AcessoArquivo;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author dudam
 */
public class Configuracoes extends javax.swing.JFrame {

    /**
     * Creates new form Configuracoes
     */
    public Configuracoes() {
        initComponents();
        carregarConfiguracoes();       
    }
  
    private void carregarConfiguracoes() {
    Configuracao CF = AcessoArquivo.le();
    text_servidor.setText(CF.getServer());
    text_porta.setText(CF.getPorta());
    text_banco.setText(CF.getBanco());
    text_usuario.setText(CF.getUser());
    text_senha.setText(CF.getPassword());
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_servidor = new javax.swing.JLabel();
        text_servidor = new javax.swing.JTextField();
        label_porta = new javax.swing.JLabel();
        text_porta = new javax.swing.JTextField();
        label_banco = new javax.swing.JLabel();
        text_banco = new javax.swing.JTextField();
        label_usuario = new javax.swing.JLabel();
        text_usuario = new javax.swing.JTextField();
        label_senha = new javax.swing.JLabel();
        text_senha = new javax.swing.JPasswordField();
        botao_cancelar = new javax.swing.JButton();
        botao_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações de acesso ao banco de dados");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        label_servidor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_servidor.setText("Servidor/IP:");

        text_servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_servidorActionPerformed(evt);
            }
        });

        label_porta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_porta.setText("Porta:");

        text_porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_portaActionPerformed(evt);
            }
        });

        label_banco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_banco.setText("Banco:");

        text_banco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bancoActionPerformed(evt);
            }
        });

        label_usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_usuario.setText("Usuário:");

        text_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usuarioActionPerformed(evt);
            }
        });

        label_senha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_senha.setText("Senha:");

        text_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_senhaActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Cancelar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_banco)
                            .addComponent(label_servidor)
                            .addComponent(label_porta)
                            .addComponent(label_usuario)
                            .addComponent(label_senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_servidor, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(text_banco)
                            .addComponent(text_usuario)
                            .addComponent(text_porta)
                            .addComponent(text_senha))
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_servidor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_porta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_banco)
                    .addComponent(text_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_usuario)
                    .addComponent(text_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_senha)
                    .addComponent(text_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_cancelar)
                    .addComponent(botao_salvar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_servidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_servidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_servidorActionPerformed

    private void text_portaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_portaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_portaActionPerformed

    private void text_bancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_bancoActionPerformed

    private void text_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_senhaActionPerformed

    private void text_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usuarioActionPerformed

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
       dispose();
    }//GEN-LAST:event_botao_cancelarActionPerformed

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
       System.out.println("Botão salvar clicado");
        
        Configuracao CF = new Configuracao();
        
        CF.setServer(text_servidor.getText());
        CF.setPorta(text_porta.getText());
        CF.setBanco(text_banco.getText());
        CF.setUser(text_usuario.getText());
         CF.setPassword(text_senha.getText());
        
        try {
             AcessoArquivo.grava(CF);
            JOptionPane.showMessageDialog(rootPane, "Alterações gravadas com sucesso!!"); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro na gravaçào do arquivo de configurações!!");
            e.printStackTrace(); // mostra erro no console
        }
        dispose();
    }//GEN-LAST:event_botao_salvarActionPerformed
        
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    Configuracao CF = AcessoArquivo.le();
    text_servidor.setText(CF.getServer());
    text_porta.setText(CF.getPorta());
    text_banco.setText(CF.getBanco());
    text_usuario.setText(CF.getUser());
    text_senha.setText(CF.getPassword());  
    }//GEN-LAST:event_formComponentShown

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        // Define o Look and Feel do sistema
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JLabel label_banco;
    private javax.swing.JLabel label_porta;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_servidor;
    private javax.swing.JLabel label_usuario;
    private javax.swing.JTextField text_banco;
    private javax.swing.JTextField text_porta;
    private javax.swing.JPasswordField text_senha;
    private javax.swing.JTextField text_servidor;
    private javax.swing.JTextField text_usuario;
    // End of variables declaration//GEN-END:variables
}
