package GUI;

import Classes.Profissional;
import DAO.DAO.ErpDAOException;
import DAO.DAO.ProfissionalDAO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class InsereProfissional extends javax.swing.JFrame {

    public InsereProfissional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label_nome = new javax.swing.JLabel();
        text_nome = new javax.swing.JTextField();
        label_sexo = new javax.swing.JLabel();
        text_especialidade = new javax.swing.JTextField();
        botao_f = new javax.swing.JRadioButton();
        botao_m = new javax.swing.JRadioButton();
        label_especialidade = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        text_telefone = new javax.swing.JTextField();
        botao_ok = new javax.swing.JButton();
        botao_cancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Profissional");

        label_nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_nome.setText("Nome:");

        label_sexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_sexo.setText("Sexo:");

        text_especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_especialidadeActionPerformed(evt);
            }
        });

        buttonGroup1.add(botao_f);
        botao_f.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_f.setText("Feminino");
        botao_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_fActionPerformed(evt);
            }
        });

        buttonGroup1.add(botao_m);
        botao_m.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_m.setText("Masculino");
        botao_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_mActionPerformed(evt);
            }
        });

        label_especialidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_especialidade.setText("Especialidade:");

        label_telefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_telefone.setText("Telefone:");

        text_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_telefoneActionPerformed(evt);
            }
        });

        botao_ok.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botao_ok.setText("Ok");
        botao_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_okMouseClicked(evt);
            }
        });
        botao_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_okActionPerformed(evt);
            }
        });

        botao_cancela.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        botao_cancela.setText("Cancela");
        botao_cancela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cancelaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_especialidade)
                    .addComponent(label_nome)
                    .addComponent(label_telefone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botao_f)
                            .addGap(43, 43, 43)
                            .addComponent(botao_m))
                        .addComponent(text_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(text_especialidade)
                        .addComponent(text_nome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(botao_cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_sexo)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_especialidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_telefone))
                        .addGap(31, 31, 31)
                        .addComponent(label_sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_m)
                            .addComponent(botao_f))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_ok)
                            .addComponent(botao_cancela))))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_especialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_especialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_especialidadeActionPerformed

    private void botao_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_mActionPerformed

    private void text_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_telefoneActionPerformed

    private void botao_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_fActionPerformed

    private void botao_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_okActionPerformed

    }//GEN-LAST:event_botao_okActionPerformed

    private void botao_cancelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cancelaMouseClicked
        dispose();
    }//GEN-LAST:event_botao_cancelaMouseClicked

    private void botao_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_okMouseClicked
        Profissional profissional = new Profissional();
        String nome_profissional, especialidade, telefone;
        char sexo = ' ';

        if (text_nome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa digitar o nome");
            return;
        } else if ((botao_f.isSelected() == false) && (botao_m.isSelected() == false)) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar o sexo");
        } else {
            nome_profissional = text_nome.getText();
            if (botao_f.isSelected() == true) {
                sexo = 'F';
            }
            if (botao_m.isSelected() == true) {
                sexo = 'M';
            }
            especialidade = text_especialidade.getText();
            telefone = text_telefone.getText();

            profissional.setNome_profissional(nome_profissional);
            profissional.setSexo(sexo);
            profissional.setEspecialidade(especialidade);
            profissional.setTelefone(telefone);

            try {
                ProfissionalDAO PDAO = new ProfissionalDAO();
                PDAO.InserirProfissional(profissional);
                JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");

            } catch (ErpDAOException ex) {
                System.out.println("problema na inserção do profissional");
            }
            dispose();
        }
    }//GEN-LAST:event_botao_okMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        // Define o Look and Feel do sistema
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsereProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsereProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsereProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsereProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsereProfissional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancela;
    private javax.swing.JRadioButton botao_f;
    private javax.swing.JRadioButton botao_m;
    private javax.swing.JButton botao_ok;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel label_especialidade;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JTextField text_especialidade;
    private javax.swing.JTextField text_nome;
    private javax.swing.JTextField text_telefone;
    // End of variables declaration//GEN-END:variables
}
