package GUI;

import Classes.Agendamento;
import Classes.Cliente;
import Classes.Procedimento;
import Classes.Profissional;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.Time;
import java.util.Date;
import DAO.DAO.AgendamentoDAO;
import DAO.DAO.ClienteDAO;
import DAO.DAO.ErpDAOException;
import DAO.DAO.ProcedimentoDAO;
import DAO.DAO.ProfissionalDAO;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.UIManager;

public class InsereAgendamento extends javax.swing.JFrame {

    private static ArrayList<Cliente> cliente = new ArrayList<>();
    ArrayList<Integer> clienteIds = new ArrayList<>();
    ArrayList<Integer> profissionalIds = new ArrayList<>();
    ArrayList<Integer> procedimentoIds = new ArrayList<>();

    /**
     * Creates new form InsereAgendamento
     */
    public InsereAgendamento() {
        initComponents();
        carregarComboClientes();
        carregarComboProfissional();
        carregarComboProcedimento();
        carregarComboStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_cliente = new javax.swing.JLabel();
        combo_box_cliente = new javax.swing.JComboBox<>();
        label_profissional = new javax.swing.JLabel();
        combo_box_profissional = new javax.swing.JComboBox<>();
        combo_box_procedimento = new javax.swing.JComboBox<>();
        label_procedimento = new javax.swing.JLabel();
        calendario = new datechooser.beans.DateChooserPanel();
        label_data = new javax.swing.JLabel();
        botao_ok = new javax.swing.JButton();
        botao_cancela = new javax.swing.JButton();
        label_hora = new javax.swing.JLabel();
        text_hora = new javax.swing.JTextField();
        combo_box_status = new javax.swing.JComboBox<>();
        label_status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Agendamento");

        label_cliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_cliente.setText("Cliente:");

        label_profissional.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_profissional.setText("Profissional:");

        label_procedimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_procedimento.setText("Procedimento:");

        label_data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_data.setText("Data:");

        botao_ok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_ok.setText("Ok");
        botao_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_okMouseClicked(evt);
            }
        });
        botao_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_okActionPerformed(evt);
            }
        });

        botao_cancela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_cancela.setText("Cancela");
        botao_cancela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cancelaMouseClicked(evt);
            }
        });

        label_hora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_hora.setText("Hora:");

        combo_box_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_statusActionPerformed(evt);
            }
        });

        label_status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_status.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_profissional)
                            .addComponent(label_cliente)
                            .addComponent(label_procedimento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_box_cliente, 0, 212, Short.MAX_VALUE)
                            .addComponent(combo_box_profissional, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_box_procedimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(botao_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(botao_cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_hora)
                            .addComponent(label_status)
                            .addComponent(combo_box_status, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_data))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_box_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_cliente)
                            .addComponent(label_data))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(label_profissional)
                                    .addComponent(combo_box_profissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_box_procedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_procedimento))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botao_cancela)
                                    .addComponent(botao_ok)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(text_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(label_status)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combo_box_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(label_hora)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_box_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_box_statusActionPerformed

    private void botao_cancelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cancelaMouseClicked
        dispose();
    }//GEN-LAST:event_botao_cancelaMouseClicked

    public void carregarComboClientes() {
        try {
            combo_box_cliente.removeAllItems();
            clienteIds.clear();

            ClienteDAO cdao = new ClienteDAO();
            ArrayList<Cliente> lista = cdao.ListarCliente();

            for (int i = 0; i < lista.size(); i++) {
                combo_box_cliente.addItem(lista.get(i).getNome_cliente());
                clienteIds.add(lista.get(i).getId_cliente());
            }

        } catch (Exception e) {
            System.out.println("Erro ao carregar clientes: " + e);
        }
    }

    public void carregarComboProfissional() {
        try {
            combo_box_profissional.removeAllItems();
            profissionalIds.clear();

            ProfissionalDAO pdao = new ProfissionalDAO();
            ArrayList<Profissional> lista = pdao.ListarProfissional();

            for (int i = 0; i < lista.size(); i++) {
                combo_box_profissional.addItem(lista.get(i).getNome_profissional());
                profissionalIds.add(lista.get(i).getId_profissional());
            }

        } catch (Exception e) {
            System.out.println("Erro ao carregar profissional: " + e);
        }
    }

    public void carregarComboProcedimento() {
        try {
            combo_box_procedimento.removeAllItems();
            procedimentoIds.clear();

            ProcedimentoDAO pdao = new ProcedimentoDAO();
            ArrayList<Procedimento> lista = pdao.ListarProcedimento();

            for (int i = 0; i < lista.size(); i++) {
                combo_box_procedimento.addItem(lista.get(i).getNome_procedimento());
                procedimentoIds.add(lista.get(i).getId_procedimento());
            }

        } catch (Exception e) {
            System.out.println("Erro ao carregar procedimento: " + e);
        }
    }

    public void carregarComboStatus() {
        combo_box_status.removeAllItems();
        combo_box_status.addItem("Agendado");
        combo_box_status.addItem("Confirmado");
        combo_box_status.addItem("Cancelado");
        combo_box_status.addItem("Concluído");
    }


    private void botao_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_okMouseClicked

        Agendamento agendamento = new Agendamento();

        int id_cliente = clienteIds.get(combo_box_cliente.getSelectedIndex());
        int id_profissional = profissionalIds.get(combo_box_profissional.getSelectedIndex());
        int id_procedimento = procedimentoIds.get(combo_box_procedimento.getSelectedIndex());

try {
    ProcedimentoDAO procDao = new ProcedimentoDAO();
    ArrayList<Procedimento> listaProcedimentos = procDao.listarProcedimentosPorProfissional(id_profissional);


    boolean pertence = listaProcedimentos.stream()
            .anyMatch(p -> p.getId_procedimento() == id_procedimento);

    if (!pertence) {
        JOptionPane.showMessageDialog(this,
            "O procedimento selecionado não pertence ao profissional escolhido!");
        return;
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erro ao validar procedimento: " + e.getMessage());
    e.printStackTrace(); 
    return;
}

        String hora = text_hora.getText().trim();
        if (hora.equals("")) {
            JOptionPane.showMessageDialog(this, "Você precisa informar a hora!");
            return;
        }

        String status = combo_box_status.getSelectedItem().toString();

        Date data_agendamento = null;

        try {
            Calendar cal = calendario.getSelectedDate();

            if (cal == null) {
                JOptionPane.showMessageDialog(this, "Você precisa selecionar uma data!");
                return;
            }

            data_agendamento = new java.sql.Date(cal.getTimeInMillis());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao ler a data!");
            return;
        }

        String horaTxt = text_hora.getText().trim();

        if (horaTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a hora no formato HH:mm (ex: 14:30).");
            return;
        }

        try {
            java.time.LocalTime lt = java.time.LocalTime.parse(horaTxt,
                    java.time.format.DateTimeFormatter.ofPattern("HH:mm"));

            java.sql.Time horaSql = java.sql.Time.valueOf(lt);
            agendamento.setHora(horaSql);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hora inválida! Use o formato HH:mm (ex: 14:30).");
            return;
        }

        agendamento.setId_cliente(id_cliente);
        agendamento.setId_profissional(id_profissional);
        agendamento.setId_procedimento(id_procedimento);
        agendamento.setData(data_agendamento);
        agendamento.setStatus(status);

        try {
            AgendamentoDAO adao = new AgendamentoDAO();
            adao.InserirAgendamento(agendamento);
            JOptionPane.showMessageDialog(this, "Agendamento registrado com sucesso!");
            dispose();
        } catch (ErpDAOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar agendamento!");
            System.out.println(ex);
        }

    }//GEN-LAST:event_botao_okMouseClicked

    private void botao_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        // Define o Look and Feel do sistema
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsereAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsereAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsereAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsereAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsereAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancela;
    private javax.swing.JButton botao_ok;
    private datechooser.beans.DateChooserPanel calendario;
    private javax.swing.JComboBox<String> combo_box_cliente;
    private javax.swing.JComboBox<String> combo_box_procedimento;
    private javax.swing.JComboBox<String> combo_box_profissional;
    private javax.swing.JComboBox<String> combo_box_status;
    private javax.swing.JLabel label_cliente;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    private javax.swing.JLabel label_procedimento;
    private javax.swing.JLabel label_profissional;
    private javax.swing.JLabel label_status;
    private javax.swing.JTextField text_hora;
    // End of variables declaration//GEN-END:variables
}
