package GUI;

import Classes.Cliente;
import DAO.DAO.ClienteDAO;
import DAO.DAO.ErpDAOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class InsereClientes extends javax.swing.JFrame {

    public InsereClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        label_nome = new javax.swing.JLabel();
        text_nome = new javax.swing.JTextField();
        label_telefone = new javax.swing.JLabel();
        text_telefone = new javax.swing.JTextField();
        label_data = new javax.swing.JLabel();
        text_cpf = new javax.swing.JTextField();
        calendario = new datechooser.beans.DateChooserPanel();
        label_cpf = new javax.swing.JLabel();
        botao_ok = new javax.swing.JButton();
        botao_cancela = new javax.swing.JButton();
        label_sexo = new javax.swing.JLabel();
        botao_f = new javax.swing.JRadioButton();
        botao_m = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserir Cliente");

        label_nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_nome.setText("Nome:");

        label_telefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_telefone.setText("Telefone:");

        label_data.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_data.setText("Data de Nascimento:");

        text_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cpfActionPerformed(evt);
            }
        });

        label_cpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_cpf.setText("Cpf:");

        botao_ok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_ok.setText("Ok");
        botao_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_okMouseClicked(evt);
            }
        });
        botao_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_okActionPerformed(evt);
            }
        });

        botao_cancela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_cancela.setText("Cancela");
        botao_cancela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botao_cancelaMouseClicked(evt);
            }
        });
        botao_cancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelaActionPerformed(evt);
            }
        });

        label_sexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_sexo.setText("Sexo:");

        buttonGroup1.add(botao_f);
        botao_f.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_f.setText("Feminino");

        buttonGroup1.add(botao_m);
        botao_m.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botao_m.setText("Masculino");
        botao_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_mActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_telefone)
                            .addComponent(label_nome)
                            .addComponent(label_cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botao_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_f))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botao_cancela, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botao_m)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(label_sexo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(label_data)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_nome))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_telefone)
                            .addComponent(text_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cpf)
                            .addComponent(text_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(label_sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_m)
                            .addComponent(botao_f))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_ok)
                            .addComponent(botao_cancela)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cpfActionPerformed

    private void botao_cancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_cancelaActionPerformed

    private void botao_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_mActionPerformed
        // 
    }//GEN-LAST:event_botao_mActionPerformed

    private void botao_cancelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_cancelaMouseClicked
        dispose();
    }//GEN-LAST:event_botao_cancelaMouseClicked

    private void botao_okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botao_okMouseClicked
        Cliente cliente = new Cliente();
        String nome_cliente, cpf, telefone;
        Date data_nascimento = null;
        char sexo = ' ';
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");

        if (text_nome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa digitar o nome");
            return;
        }

        if (!botao_f.isSelected() && !botao_m.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar o sexo");
            return;
        }

        nome_cliente = text_nome.getText();
        cpf = text_cpf.getText();
        telefone = text_telefone.getText();

        if (botao_f.isSelected()) {
            sexo = 'F';
        }
        if (botao_m.isSelected()) {
            sexo = 'M';
        }

        try {
            Calendar cal = calendario.getSelectedDate();
            if (cal == null) {
                JOptionPane.showMessageDialog(this, "Você precisa selecionar a data de nascimento!");
                return;
            }
            data_nascimento = cal.getTime();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao ler a data de nascimento!");
            return;
        }

        cliente.setNome_cliente(nome_cliente);
        cliente.setTelefone(telefone);
        cliente.setCpf(cpf);
        cliente.setData_nascimento(data_nascimento);
        cliente.setSexo(sexo);

        try {
            ClienteDAO CDAO = new ClienteDAO();
            CDAO.InserirCliente(cliente);
            JOptionPane.showMessageDialog(rootPane, "Inserção efetuada com sucesso!!");
            dispose();
        } catch (ErpDAOException ex) {
            System.out.println("problema na inserção do cliente: " + ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao inserir cliente!");
        }

    }//GEN-LAST:event_botao_okMouseClicked

    private void botao_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        // Define o Look and Feel do sistema
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsereClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsereClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsereClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsereClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsereClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancela;
    private javax.swing.JRadioButton botao_f;
    private javax.swing.JRadioButton botao_m;
    private javax.swing.JButton botao_ok;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private datechooser.beans.DateChooserPanel calendario;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JTextField text_cpf;
    private javax.swing.JTextField text_nome;
    private javax.swing.JTextField text_telefone;
    // End of variables declaration//GEN-END:variables
}
