package GUI;

import Classes.Cliente;
import DAO.DAO.ClienteDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.DAO.ClienteDAO;
import Classes.Cliente;
import java.util.Calendar;
import java.util.Date;
import javax.swing.UIManager;

public class TelaCliente extends javax.swing.JFrame {

    private ArrayList<Integer> clienteIds = new ArrayList<>();

    public TelaCliente() {
    initComponents();
    
    tabela_clientes.setDefaultEditor(Object.class, null);
    carregarComboClientes();
    
      if (combo_box_cliente.getItemCount() > 0) {
        combo_box_cliente.setSelectedIndex(0); 
        combo_box_clienteActionPerformed(null); 
    }

    tabela_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {

            int click = evt.getClickCount();

            if (click == 1) {
                carregarDataNoCalendario();
            }
            else if (click == 2) {
                tabela_clientesMouseClicked(evt);
            }
        }
    });
    
    tabela_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseReleased(java.awt.event.MouseEvent evt) {
        if (evt.isPopupTrigger()) { 
            int row = tabela_clientes.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                tabela_clientes.setRowSelectionInterval(row, row); 

                int comboIndex = combo_box_cliente.getSelectedIndex();
                int idCliente = clienteIds.get(comboIndex);

                int confirm = JOptionPane.showConfirmDialog(
                        TelaCliente.this, 
                        "Tem certeza que deseja excluir este cliente?",
                        "Confirmar exclusão",
                        JOptionPane.YES_NO_OPTION
                );

                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        ClienteDAO dao = new ClienteDAO();
                        dao.ExcluirCliente(idCliente);
                        JOptionPane.showMessageDialog(TelaCliente.this, "Cliente excluído com sucesso!");

                        carregarComboClientes();
                        ((DefaultTableModel) tabela_clientes.getModel()).setRowCount(0);

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(TelaCliente.this, "Erro ao excluir: " + e.getMessage());
                    }
                }
            }
        }
    }
});

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        acessoArquivo1 = new DAO.Util.AcessoArquivo();
        combo_box_cliente = new javax.swing.JComboBox<>();
        calendario = new datechooser.beans.DateChooserPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_clientes = new javax.swing.JTable();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Clientes");

        combo_box_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_clienteActionPerformed(evt);
            }
        });

        calendario.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                calendarioOnSelectionChange(evt);
            }
        });

        tabela_clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "Telefone", "Cpf"
            }
        ));
        tabela_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(combo_box_cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combo_box_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_box_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_clienteActionPerformed
        int index = combo_box_cliente.getSelectedIndex();
      if (index < 0 || clienteIds.isEmpty()) {
            return;      
        }
        int idCliente = clienteIds.get(index);
    carregarTabelaCliente(idCliente);    }//GEN-LAST:event_combo_box_clienteActionPerformed

    private void tabela_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_clientesMouseClicked

    if (evt.getClickCount() != 2) return;

    try {
        int indexCombo = combo_box_cliente.getSelectedIndex();
        if (indexCombo < 0) return;

        int id = clienteIds.get(indexCombo);

        int index = tabela_clientes.getSelectedRow();

        if (index < 0) return;

        String nome = tabela_clientes.getValueAt(index, 0).toString();
        char sexo = tabela_clientes.getValueAt(index, 1).toString().charAt(0);
        String telefone = tabela_clientes.getValueAt(index, 2).toString();
        String cpf = tabela_clientes.getValueAt(index, 3).toString();

        Calendar cal = calendario.getSelectedDate();
        Date dataNascimento = cal.getTime();

        String novoNome = JOptionPane.showInputDialog(this, "Novo nome:", nome);
        if (novoNome == null || novoNome.trim().isEmpty()) return;

        String novoTelefone = JOptionPane.showInputDialog(this, "Novo telefone:", telefone);
        if (novoTelefone == null) return;

        String novoCpf = JOptionPane.showInputDialog(this, "Novo CPF:", cpf);
        if (novoCpf == null) return;

        Cliente cliente = new Cliente();
        cliente.setId_cliente(id);
        cliente.setNome_cliente(novoNome);
        cliente.setSexo(sexo);
        cliente.setTelefone(novoTelefone);
        cliente.setCpf(novoCpf);
        cliente.setData_nascimento(dataNascimento);

        ClienteDAO dao = new ClienteDAO();
        dao.AlterarCliente(cliente);

        carregarTabelaCliente(id);

        tabela_clientes.clearSelection();

        JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar cliente: " + e.getMessage());
    }
    }//GEN-LAST:event_tabela_clientesMouseClicked

    private void calendarioOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_calendarioOnSelectionChange
    int comboIndex = combo_box_cliente.getSelectedIndex();
    if (comboIndex < 0) return; 

    int id = clienteIds.get(comboIndex);

    try {
        Calendar cal = calendario.getSelectedDate();
        Date novaData = cal.getTime();

        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.ProcurarCliente(id);

        if (cliente != null) {
            cliente.setData_nascimento(novaData); 
            dao.AlterarCliente(cliente);
            System.out.println("Data atualizada: " + novaData);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar data: " + ex.getMessage());
    }

    }//GEN-LAST:event_calendarioOnSelectionChange

    private void carregarTabelaCliente(int idCliente) {
    try {
        ClienteDAO dao = new ClienteDAO();
        Cliente c = dao.ProcurarCliente(idCliente);

        DefaultTableModel modelo = (DefaultTableModel) tabela_clientes.getModel();
        modelo.setRowCount(0);

        modelo.addRow(new Object[]{
            c.getNome_cliente(),
            c.getSexo(),
            c.getTelefone(),
            c.getCpf()
        });

        if (c.getData_nascimento() != null) {
            Calendar cal = Calendar.getInstance();
            cal.setTime(c.getData_nascimento());
            calendario.setSelectedDate(cal);
        }

    } catch (Exception e) {
        System.out.println("Erro ao carregar tabela: " + e);
    }
}

    private void carregarDataNoCalendario() {

    int index = tabela_clientes.getSelectedRow();
    if (index < 0) return;

    int id = clienteIds.get(index);

    try {
        ClienteDAO dao = new ClienteDAO();
        Cliente cliente = dao.ProcurarCliente(id);

        if (cliente != null && cliente.getData_nascimento() != null) {

            Calendar cal = Calendar.getInstance();
            cal.setTime(cliente.getData_nascimento());

            calendario.setSelectedDate(cal);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar data: " + e.getMessage());
    }
}

    
    private void carregarComboClientes() {
        try {
            combo_box_cliente.removeAllItems();
            clienteIds.clear();

            ClienteDAO dao = new ClienteDAO();
            ArrayList<Cliente> lista = dao.ListarCliente();

            for (int i = 0; i < lista.size(); i++) {
                combo_box_cliente.addItem(lista.get(i).getNome_cliente());
                clienteIds.add(lista.get(i).getId_cliente());
            }

        } catch (Exception e) {
            System.out.println("Erro ao carregar clientes: " + e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DAO.Util.AcessoArquivo acessoArquivo1;
    private datechooser.beans.DateChooserPanel calendario;
    private javax.swing.JComboBox<String> combo_box_cliente;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_clientes;
    // End of variables declaration//GEN-END:variables
}
