package GUI;

import java.util.ArrayList;
import DAO.DAO.ProfissionalDAO;
import Classes.Profissional;
import DAO.DAO.ErpDAOException;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dudam
 */
public class TelaProfissional extends javax.swing.JFrame {

    private ArrayList<Integer> profissionalIds = new ArrayList<>();

    public TelaProfissional() {
        initComponents();
        tabela_profissional.setDefaultEditor(Object.class, null);

        carregarProfissionaisNoCombo();

        if (!profissionalIds.isEmpty()) {
            combo_box_profissional.setSelectedIndex(0);
            carregarTabelaProfissional(profissionalIds.get(0));
        }

        tabela_profissional.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    tabela_profissionalMouseClicked(evt);
                }
            }
        });

        tabela_profissional.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger()) {
                    mostrarConfirmacaoExclusao(evt);
                }
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger()) {
                    mostrarConfirmacaoExclusao(evt);
                }
            }
        });
    }

    private void mostrarConfirmacaoExclusao(MouseEvent evt) {
        int linha = tabela_profissional.rowAtPoint(evt.getPoint());
        if (linha < 0) {
            return;
        }

        tabela_profissional.setRowSelectionInterval(linha, linha);

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este profissional?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {

            int index = combo_box_profissional.getSelectedIndex();
            int id = profissionalIds.get(index);

            try {
                ProfissionalDAO dao = new ProfissionalDAO();
                dao.ExcluirProfissional(id);

                carregarProfissionaisNoCombo();

                if (!profissionalIds.isEmpty()) {
                    combo_box_profissional.setSelectedIndex(0);
                    carregarTabelaProfissional(profissionalIds.get(0));
                }

                JOptionPane.showMessageDialog(this, "Profissional excluído com sucesso!");

            } catch (ErpDAOException ex) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir profissional: " + ex.getMessage());
            }

        }
    }

    private void carregarProfissionaisNoCombo() {
        try {
            combo_box_profissional.removeAllItems();
            profissionalIds.clear();

            ProfissionalDAO dao = new ProfissionalDAO();
            ArrayList<Profissional> lista = dao.ListarProfissional();

            for (Profissional p : lista) {
                combo_box_profissional.addItem(p.getNome_profissional());
                profissionalIds.add(p.getId_profissional());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar profissionais: " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_box_profissional = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_profissional = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Profissional");

        combo_box_profissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_box_profissionalActionPerformed(evt);
            }
        });

        tabela_profissional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "Especialidade", "Telefone"
            }
        ));
        tabela_profissional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_profissionalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_profissional);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combo_box_profissional, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(combo_box_profissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_box_profissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_box_profissionalActionPerformed
        int index = combo_box_profissional.getSelectedIndex();
        if (index < 0 || profissionalIds.isEmpty()) {
            return;
        }

        int id = profissionalIds.get(index);
        carregarTabelaProfissional(id);
    }//GEN-LAST:event_combo_box_profissionalActionPerformed


    private void tabela_profissionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_profissionalMouseClicked
        if (evt.getClickCount() == 2) {

            try {
                int index = combo_box_profissional.getSelectedIndex();
                if (index < 0) {
                    return;
                }

                int id = profissionalIds.get(index);

                int row = tabela_profissional.getSelectedRow();
                if (row < 0) {
                    return;
                }

                String nome = tabela_profissional.getValueAt(row, 0).toString();
                String sexo = tabela_profissional.getValueAt(row, 1).toString();
                String especialidade = tabela_profissional.getValueAt(row, 2).toString();
                String telefone = tabela_profissional.getValueAt(row, 3).toString();

                String novoNome = JOptionPane.showInputDialog(this, "Novo nome:", nome);
                if (novoNome == null || novoNome.trim().isEmpty()) {
                    return;
                }

                String novoSexo = JOptionPane.showInputDialog(this, "Sexo (M/F):", sexo);
                if (novoSexo == null || novoSexo.trim().isEmpty()) {
                    return;
                }

                String novaEsp = JOptionPane.showInputDialog(this, "Nova especialidade:", especialidade);
                if (novaEsp == null || novaEsp.trim().isEmpty()) {
                    return;
                }

                String novoTel = JOptionPane.showInputDialog(this, "Novo telefone:", telefone);
                if (novoTel == null) {
                    return;
                }

                Profissional p = new Profissional();
                p.setId_profissional(id);
                p.setNome_profissional(novoNome);
                p.setSexo(novoSexo.charAt(0));
                p.setEspecialidade(novaEsp);
                p.setTelefone(novoTel);

                ProfissionalDAO dao = new ProfissionalDAO();
                dao.AlterarProfissional(p);

                carregarTabelaProfissional(id);

                JOptionPane.showMessageDialog(this, "Profissional atualizado com sucesso!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar profissional: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_tabela_profissionalMouseClicked

    private void carregarTabelaProfissional(int id) {
        try {
            ProfissionalDAO dao = new ProfissionalDAO();
            Profissional p = dao.ProcurarProfissional(id);
            DefaultTableModel modelo = (DefaultTableModel) tabela_profissional.getModel();
            modelo.setRowCount(0);

            if (p != null) {
                modelo.addRow(new Object[]{
                    p.getNome_profissional(),
                    p.getSexo(),
                    p.getEspecialidade(),
                    p.getTelefone()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar profissional: " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProfissional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_box_profissional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_profissional;
    // End of variables declaration//GEN-END:variables
}
