
package GUI;

import Classes.Procedimento;
import Classes.Profissional;
import DAO.DAO.ProcedimentoDAO;
import DAO.DAO.ProfissionalDAO;
import DAO.DAO.ProfissionalProcedimentoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dudam
 */
public class VincularProcedimentoProfissional extends javax.swing.JFrame {

        private ArrayList<Integer> profissionalIds = new ArrayList<>();
private ArrayList<Integer> procedimentoIdsCombo = new ArrayList<>(); 
private ArrayList<Integer> procedimentoIdsTabela = new ArrayList<>(); 

    /**
     * Creates new form VincularProcedimentoProfissional
     */
   public VincularProcedimentoProfissional() {
    initComponents();
    carregarProfissionais();
    carregarProcedimentos();
}
   
   private void carregarProfissionais() {
    try {
        ProfissionalDAO dao = new ProfissionalDAO();
        ArrayList<Profissional> lista = dao.ListarProfissional();

        combo_profissional.removeAllItems();
        profissionalIds.clear();

        for (Profissional p : lista) {
            combo_profissional.addItem(p.getNome_profissional());
            profissionalIds.add(p.getId_profissional());
        }

        if (!profissionalIds.isEmpty()) {
            combo_profissional.setSelectedIndex(0); 
            carregarTabelaVinculos(profissionalIds.get(0));
        }

        combo_profissional.addActionListener(evt -> {
            int index = combo_profissional.getSelectedIndex();
            if (index >= 0) {
                int idProf = profissionalIds.get(index);
                carregarTabelaVinculos(idProf);
            }
        });

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar profissionais");
    }
}
   
private void carregarProcedimentos() {
    try {
        ProcedimentoDAO dao = new ProcedimentoDAO();
        ArrayList<Procedimento> lista = dao.ListarProcedimento();

        combo_procedimento.removeAllItems();
        procedimentoIdsCombo.clear(); 

        for (Procedimento p : lista) {
            combo_procedimento.addItem(p.getNome_procedimento());
            procedimentoIdsCombo.add(p.getId_procedimento());
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar procedimentos");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_profissional = new javax.swing.JComboBox<>();
        combo_procedimento = new javax.swing.JComboBox<>();
        btn_adicionar = new javax.swing.JToggleButton();
        btn_remover = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_vinculos = new javax.swing.JTable();
        label_profissional = new javax.swing.JLabel();
        label_procedimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vincular Procedimentos a Profissionais");

        btn_adicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_remover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        tabela_vinculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Procedimento", "Duração", "Preço"
            }
        ));
        jScrollPane1.setViewportView(tabela_vinculos);

        label_profissional.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_profissional.setText("Profissional:");

        label_procedimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_procedimento.setText("Procedimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_adicionar)
                        .addGap(43, 43, 43)
                        .addComponent(btn_remover))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(combo_profissional, 0, 247, Short.MAX_VALUE)
                        .addComponent(label_profissional)
                        .addComponent(label_procedimento)
                        .addComponent(combo_procedimento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(label_profissional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_profissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(label_procedimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_procedimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_adicionar)
                            .addComponent(btn_remover))))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
int idProf = profissionalIds.get(combo_profissional.getSelectedIndex());
    int idProc = procedimentoIdsCombo.get(combo_procedimento.getSelectedIndex());

    try {
        ProfissionalProcedimentoDAO dao = new ProfissionalProcedimentoDAO();

        ArrayList<Procedimento> listaVinculos = dao.ListarVinculos(idProf);
        boolean jaVinculado = listaVinculos.stream()
                                    .anyMatch(p -> p.getId_procedimento() == idProc);
        if (jaVinculado) {
            JOptionPane.showMessageDialog(this, "Este vínculo já existe!");
            return; 
        }

        dao.inserirVinculo(idProf, idProc);
        JOptionPane.showMessageDialog(this, "Vínculo adicionado!");
        carregarTabelaVinculos(idProf);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_adicionarActionPerformed

private void carregarTabelaVinculos(int idProf) {
    try {
        ProfissionalProcedimentoDAO dao = new ProfissionalProcedimentoDAO();
        ArrayList<Procedimento> lista = dao.ListarVinculos(idProf);

DefaultTableModel model = new DefaultTableModel(
    new Object[]{"Procedimento", "Duração", "Preço"}, 0
) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // nenhuma célula será editável
    }
};
tabela_vinculos.setModel(model);
        model.setRowCount(0);

        
        
       procedimentoIdsTabela.clear();
for (Procedimento p : lista) {
    model.addRow(new Object[]{
        p.getNome_procedimento(),
        p.getDuracao(),
        p.getPreco()
    });
    procedimentoIdsTabela.add(p.getId_procedimento());
}


    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao carregar vínculos");
        e.printStackTrace(); 
    }
}

    
    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
    int linha = tabela_vinculos.getSelectedRow();
    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um vínculo!");
        return;
    }

    int idProf = profissionalIds.get(combo_profissional.getSelectedIndex());
    int idProc = procedimentoIdsTabela.get(linha); 

    try {
        ProfissionalProcedimentoDAO dao = new ProfissionalProcedimentoDAO();
        dao.removerVinculo(idProf, idProc);

        JOptionPane.showMessageDialog(this, "Vínculo removido!");
        carregarTabelaVinculos(idProf);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        e.printStackTrace(); 
    }
    }//GEN-LAST:event_btn_removerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         try {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (Exception e) {
        e.printStackTrace();
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VincularProcedimentoProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VincularProcedimentoProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VincularProcedimentoProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VincularProcedimentoProfissional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VincularProcedimentoProfissional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_adicionar;
    private javax.swing.JToggleButton btn_remover;
    private javax.swing.JComboBox<String> combo_procedimento;
    private javax.swing.JComboBox<String> combo_profissional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_procedimento;
    private javax.swing.JLabel label_profissional;
    private javax.swing.JTable tabela_vinculos;
    // End of variables declaration//GEN-END:variables
}
